// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hroosailxylwmkzkgtwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyb29zYWlseHlsd21remtndHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzE3NzUsImV4cCI6MjA2Njg0Nzc3NX0.zn_lCavRE3_EU9uolxqOTi63rTHdI3wBHsiPOz4stz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});